### ISSUE TITLE
Linkovi do postavki i rešenja zadataka nemaju smisla kod štampanja

### ISSUE THREAD

**Issue by Asha20** [KockaAdmiralac/OS1-kolokvijumi#1]
Trenutno, ispod svakog zadatka stoje dva linka koja vode do originalne postavke i rešenja tog zadatka na sajtu predmeta. Ovo je okej ako neko čita PDF preko kompjutera, ali u štampanom formatu linkovi samo zauzimaju prostor na papiru. Moja neka gruba procena je da dokument može da se skrati za oko 13 stranica (5%) bez ovih linkova.

Možda kao rešenje mogu da se generišu dva dokumenta tipa `combined-web.pdf` sa linkovima i `combined-print.pdf` bez njih?

**Comment by KockaAdmiralac** [comment]
Ovo bi trebalo da je sada [ispravljeno](https://github.com/KockaAdmiralac/OS1-kolokvijumi/commit/d6cc87720ecacc8d65b1e85e88c4b4261a4852ad) i [objavljeno](https://github.com/KockaAdmiralac/OS1-kolokvijumi/releases/tag/v1.0.1) (procena je bila dobra, 14 stranica je sačuvano). Hvala na sugestiji!
