### ISSUE TITLE
Greška u postavci - 3. zadatak, prvi kolokvijum, april 2009

### ISSUE THREAD

**Issue by AkileePikilee** [KockaAdmiralac/OS1-kolokvijumi#3]
Greška u postavci i rešenju:
U 2. tabeli, Virtualna adresa, 5. kolona:
Piše 303001E2, trebalo bi 403001E2

**Comment by KockaAdmiralac** [comment]
Ovo je sada ispravljeno u https://github.com/KockaAdmiralac/OS-kolokvijumi/commit/328a94c309d20cae6de427803b463c7f12fe7896, koji je objavljen u [v1.1.4](https://github.com/KockaAdmiralac/OS-kolokvijumi/releases/tag/1.1.4). Hvala!
